### ISSUE TITLE
Help choosing new gomacro license?

### ISSUE THREAD

**Issue by cosmos72** [gopherdata/gophernotes#109]
In https://github.com/cosmos72/gomacro/issues/14 I am collecting feedback and opinions to choose a new license for gomacro.

Reason: @glycerine correctly pointed out that LGPL does not work well for statically linked code as Go is - it becomes almost identical to GPL - i.e. more restrictive than what I intended.

The best candidate is currently [MPL 2.0](https://www.mozilla.org/en-US/MPL/2.0/), and I am interested in feedback from gophernote authors :)

I did a quick analysis of MPL 2.0 (note: IANAL) and it would open the following possibilities for a "larger work that includes MPL code" as gophernotes would become:
1. keep the current LGPL v3+
2. switch to MPL v2.0
3. switch to GPL v3+
4. switch to any other license, including commercial, BSD/MIT... as long as MPL source code (= gomacro) remains MPL and any modifications to MPL source code are published

Ideas, suggestions, comments ?

**Comment by SpencerPark** [comment]
Hi @cosmos72, I think MPL v2.0 is a good compromise. I've been a fan of MIT for stuff I release as my intentions with most open source projects is to provide as much freedom as possible but your concerns addressed on the original issue about why not MIT/BSD makes perfect sense and is totally understandable. Actually it is making me question my license choices because MPL is looking very nice. It seems to capture my philosophy as an open source developer very well.

As gophernotes is an open source project as well, meeting the requirements for source availability is no problem and of course we are happy to make sure you are getting the credit you deserve including sharing where others can find your project. Having a license enforcing that is great. The license is also non-viral to my knowledge so we are free to pick something else should need be which IMO is really important for using an open source project even if not necessary at the moment. Like in all these license comments I do need to add IANAL as well :)

**Comment by cosmos72** [comment]
License changed to MPL 2.0
