### ISSUE TITLE
license: revert to MIT

### ISSUE THREAD

**Issue by sbinet** [gopherdata/gophernotes#126]
now that `gomacro` isn't LGPL anymore, couldn't we revert to the previous LICENCE (MIT) ?

@dwhitena @SpencerPark @cosmos72

**Comment by sbinet** [comment]
see: https://github.com/gopherdata/gophernotes/blob/e779a2a956d828c37b45081bd92b6ab52b0e88ed/LICENSE.md

**Comment by cosmos72** [comment]
From the point of view of license compatibility, there are no obstacles - see for example what I wrote in #109.

I am a bit more perplexed by two other considerations:
1. do I remember correctly that gophernotes contributors are expected to sign the [Google CLA](https://cla.developers.google.com/about) for their contributions to gophernotes ?
2. only the copyright owner (or owners) can change the license. Licensees can only do so if the original license allows that. Who is (are) the copyright owner(s): all the contributors? Depends on the answer to question 1. ?

**Comment by SpencerPark** [comment]
I don't think everyone on the list signed the CLA, does this mean we need everyone to say ok before changing the license? https://github.com/racket/racket/issues/1570 seems to have been in the exact same situation we are in but luckily our list is a bit smaller. 

Also many contributions were before the switch from MIT to LGPL, according to [github's TOS](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) my understanding is that those contributions are licensed under MIT which makes the list of people to track down even smaller.

**Comment by SpencerPark** [comment]
To kick this off I've put together a list of contributors since the new license. I think it should be fine for everyone to make a quick reply saying they give permission to license their contributions under [MIT](https://opensource.org/licenses/MIT). IANAL so any expertise on the correct way to upgrade a license like this, are more than welcome!

If you don't want to license under MIT it would also be really helpful to suggest another license and/or motivation as to why not so we can come to an agreement. I also realize that not everyone on this list has contributed directly to the source code but contributions were made other places and so it would be great to collect the permissions regardless :)

Lastly I will write a short statement similar to what they are doing over at racket but if anyone has a suggestion on changing it, please do!

I give permission to license my contributions to gophernotes under the MIT license.

@dwhitena 
@SpencerPark
@takluyver 
@kortschak 
@arfon 
@cosmos72 
@QuLogic 
@sbinet

**Comment by sbinet** [comment]
Thanks for getting the ball rolling.

I give permission to license my contributions to gophernotes under the MIT license.

**Comment by cosmos72** [comment]
Thanks for collecting the list of contributors @SpencerPark !

I give permission to license my contributions to gophernotes under the MIT license.
 
For clarity and completeness: I do *not* give permission to license my contributions to gophernotes *dependencies* under the MIT license: each dependency (cosmos72/gomacro, peterh/liner...) has its own license already, and my contributions to them are under their respective licenses.

**Comment by arfon** [comment]
I give permission to license my contributions to gophernotes under the MIT license.

**Comment by kortschak** [comment]
I give permission to license my contributions to gophernotes under the MIT license.

**Comment by takluyver** [comment]
I give permission to license my contributions to gophernotes under the MIT license.

**Comment by dwhitena** [comment]
I give permission to license my contributions to gophernotes under the MIT license.

Looks like we are just waiting on @QuLogic. @QuLogic do you have any issues here?

**Comment by QuLogic** [comment]
Sorry for the delay; I forgot what I even did here...

I give permission to license my contributions to gophernotes under the MIT license.

**Comment by sbinet** [comment]
as everybody is in agreement, I've PR'd up:
- https://github.com/gopherdata/gophernotes/pull/139
