### ISSUE TITLE
repl: print and println not displaying output

### ISSUE THREAD

**Issue by sbinet** [gopherdata/gophernotes#149]
`print` and `println` are pre-declared identifiers that I have been using in some of my neugram.io-based notebooks.
see:
- https://play.golang.org/p/5z8Fram3jgz

converting these notebooks to `gomacro` fails, as it seems like only `stdout` is captured (and they print to `stderr`.)

could this be added?

thanks :)

**Comment by SpencerPark** [comment]
This is a little strange because the kernel redirects stderr the same way it redirects stdout. see https://github.com/gopherdata/gophernotes/blob/master/kernel.go#L359. Also travis says that the `TestPrintStderr` is passing. 

I just tried the following which printed fine. Maybe this is an issue with the `println` implementation in gomacro?

```Go
import "fmt"
import "os"
os.Stderr.WriteString("Hello stderr")
```
