### ISSUE TITLE
Extra line in the outputs

### ISSUE THREAD

**Issue by hajsf** [gopherdata/gophernotes#217]
In all my outputs I get extra line showing output length and <nil>, which looks for me as (string, error) , as underlined below is my understandin correct, and is this an optional output?

![image](https://user-images.githubusercontent.com/46838626/91645593-0971f280-ea4f-11ea-9a3d-d9bf3c36067b.png)

**Comment by cosmos72** [comment]
Hi @hajsf,
this is intentional. The `Out[n]` lines you are seeing list the return values of the evaluated expressions.

It can be confusing when the expressions also write to standard output / standard error - `fmt.Printf` returns two values: the number of bytes written and any error.

It should be clearer from the example below, which do not have side effects
![image](https://user-images.githubusercontent.com/1947270/91661028-c6a92c80-ead9-11ea-9ae9-3c407737418c.png)
