### ISSUE TITLE
[Question] non-declaration statement outside function body

### ISSUE THREAD

**Issue by tejas-kale** [gopherdata/gophernotes#226]
Hi,

I have just started learning Go and the following code (saved as `cards.go`), when executed using an IDE fails with the error `./cards.go:5:1: syntax error: non-declaration statement outside function body`.

```
package main

import "fmt"

deckSize := 20

func main() {
	fmt.Println(deckSize)
}
```

But the same piece of code when run in a Jupyter cell works fine.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/1353180/104729535-939cc800-575e-11eb-8be8-1d50b098ec57.png">

So, I am curious to know what happens under the hood in `gophernotes` which allows the Jupyter cell shown above to run fine. Thanks.

**Comment by cosmos72** [comment]
This is an intentional extension: since `gophernotes` is interactive, the compile and runtime phases are interleaved
and allowing statements and expressions at top-level is both useful and necessary:

it's useful because `gophernotes` can also be used as a calculator - for example you can execute `7 + 12` or `"foo" + "bar"`

it's also necessary because as minimum you need a way to execute the functions you created - there is no separate runtime that will execute your `main()`

**Comment by tejas-kale** [comment]
@cosmos72 Thanks for the explanation. It helps me understand the difference between `gophernotes` and the regular compile and run execution of Go. Closing the issue.
