### ISSUE TITLE
method `String()` not picked up by compiled code

### ISSUE THREAD

**Issue by spolischook** [gopherdata/gophernotes#228]
There is an example of code snippet that have different result of `go run` and gophernotes:
```go
type Direction int

const (
	North Direction = iota
	East
	South
	West
)

func (d Direction) String() string {
	return [...]string{"North", "East", "South", "West"}[d]
}

func main() {
	fmt.Print(East)
}
```
`gophernotes` example:
![Selection_412](https://user-images.githubusercontent.com/1978331/107631892-67e20480-6c6e-11eb-9929-5e37c931d69f.png)

`go run` example:
![Selection_413](https://user-images.githubusercontent.com/1978331/107631960-821be280-6c6e-11eb-9437-1ba73bc41d22.png)

**Comment by cosmos72** [comment]
This has the same root cause as #225
i.e. new named types created by the interpreter are emulated,
and their methods - in this case `Direction.toString()` - are visible only by interpreted code.

It's also equally unfixable, at least until Go standard library provides a mechanism
to create new named types at runtime and attach methods to them.

A partial workaround is to replace `fmt.Print(East)` with `fmt.Println(East.String())`

**Comment by spolischook** [comment]
Thanks for explanation
