### ISSUE TITLE
Running in VSCode using jupyter

### ISSUE THREAD

**Issue by JCzz** [gopherdata/gophernotes#256]
Hi

Will it be possible to tun this in VSCode, using the following:

https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter

**Comment by cosmos72** [comment]
It says "A Visual Studio Code extension that provides basic notebook support for language kernels that are supported in Jupyter Notebooks today" so yes, in theory it may work.

I think nobody tried gophernotes with it yet, so you're welcome to post here the results of any attempt you may want to do.

**Comment by Ale0x78** [comment]
I keep getting 
```
The 'go' kernel is not available. Please pick another suitable kernel instead, or install that kernel. 
```
When inside VS-Code (no issues in JupyterLab though). Any chance anyone else has run into this issue? 
I tried adding it into trusted kernal's with
```
"jupyter.kernels.trusted": ["~/Library/Jupyter/kernels/gophernotes"]
```
But still no luck.

**Comment by Ale0x78** [comment]
NVM looks like running a JupyterLab server via the terminal and then connecting to it works. Probably some kind of a config thing I am missing in VSCode.

**Comment by Nigel2392** [comment]
To add to @Igorgro, for me it is working great. Except:
1. There is no syntax highlighting.
2. The VSCode [Go to Definition](https://code.visualstudio.com/Docs/editor/editingevolved#_go-to-definition) functionality does not work (Among others functionality.)

**Comment by joelschutz** [comment]
I'd been the entire day trying to find a way to do it. It's not a Kernel issue, [go-kernel](https://gitlab.com/ethan.reesor/vscode-notebooks/go-kernel) has the same issue.

The main problem is in the VSCode LSP protocol itself, it sends a path to the server to analyze. On the [vscode-python](https://github.com/microsoft/vscode-python) they created a hack in the extension to concat a file before sending it the language server.
![Captura de tela de 2023-02-09 21-32-08](https://user-images.githubusercontent.com/49206635/217970719-7ac3b5b1-34df-4dd0-8bc5-0fb80e03ad58.png)

I don't think it's worth it to create something like it for Go, that's why in trying jupyter now.

**Comment by Igorgro** [comment]
For unknown reason it just stopped working in 1.75 version of vscode. Just no any output nor errors. 
![image](https://user-images.githubusercontent.com/22894169/218341660-e0fcb9cb-1359-4220-a549-10a676538779.png)

**Comment by joelschutz** [comment]
Following up on my previous comment:

1. The *hack* is the only way to work with notebooks on most of the languages servers currently. And both VSCode and Jupyter use it in Python.
2. LSP added support for notebook at version [3.17(latest)](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/). This mean that it could be possible to remove the *hack*.
3. Both gopls and vscode-go are mantained by Google, and notebook support is not a priority.

Maybe it would be possible to use [this](https://github.com/microsoft/lsp-notebook-concat) to create a middleware to handle notebooks.
