### ISSUE TITLE
fails to import "sync" package

### ISSUE THREAD

**Issue by sudipidus** [gopherdata/gophernotes#263]
While I try to import "sync" package I get the following error

```bash
Converter.Type(): unsupported types.Type: *types.TypeParam
```

I randomly tried importing other packages and it works just fine.

What am I missing?

ps: adding this as an issue since I don't see discussion column

**Comment by cosmos72** [comment]
That's because importing generic types and generic functions is not yet supported,
and gophernotes@v0.7.5 chokes on them.

There's a partial fix in the latest version, which just **skips** generic types and generic functions while importing a package.
To install the latest version, follow the usual [installation instructions](https://github.com/gopherdata/gophernotes?tab=readme-ov-file#installation) but replace `@v0.7.5` with `@latest`
