### ISSUE TITLE
jupyterlab expression result never returns ( works with notebook )

### ISSUE THREAD

**Issue by stoneyv** [gopherdata/gophernotes#99]
Code expressions are evaluated and return a response with jupyter notebook, but never return with jupyterlab.  I increased the log level to 'INFO' and then 'DEBUG', but I was not able to learn much from the increased output. 
jupyter notebook --version
5.3.1
jupyter lab --version
0.31.2
libzmq version 4.2.4 was built on ubuntu 17.10 from master on github.
jupyter notebook  --log-level='INFO'
jupyter lab  --log-level='INFO'
```
a := 1
import "fmt"
fmt.Println(a)
a := 2
fmt.Println(a)
```
Jupyter notebook expressions are evaluated and output is returned
![gophernotes_jupyter_notebook_test](https://user-images.githubusercontent.com/2159740/36064779-4028c09e-0e45-11e8-922e-6bc509f69f55.png)
Jupyter lab expressions do not return 
(note the asterisks to the left of the first three cells and no output from the fmt.Println(a) expression.
![gophernotes_jupyter_lab_test](https://user-images.githubusercontent.com/2159740/36064783-51b6c8ba-0e45-11e8-9394-0aaff5235033.png)

logged output from jupyterlab on level 'INFO'
```
stoney@workstation:~/Desktop$ jupyter lab --log-level='INFO'
[I 09:26:19.361 LabApp] JupyterLab beta preview extension loaded from /home/stoney/anaconda3/lib/python3.6/site-packages/jupyterlab
[I 09:26:19.361 LabApp] JupyterLab application directory is /home/stoney/anaconda3/share/jupyter/lab
[I 09:26:19.366 LabApp] Serving notebooks from local directory: /home/stoney/Desktop
[I 09:26:19.366 LabApp] 0 active kernels
[I 09:26:19.366 LabApp] The Jupyter Notebook is running at:
[I 09:26:19.366 LabApp] http://localhost:8888/?token=7f315752e2fcbbf3f30abba307404525c9e511b67adac340
[I 09:26:19.366 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:26:19.367 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7f315752e2fcbbf3f30abba307404525c9e511b67adac340
[I 09:26:19.804 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[3980:4018:0210/092619.844347:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.
Created new window in existing browser session.
[I 09:26:20.428 LabApp] Build is up to date
[I 09:26:20.950 LabApp] Kernel started: 299cee67-abd9-4a86-8c16-8d39af8c23bf
[I 09:26:20.963 LabApp] Adapting to protocol v5.0 for kernel 299cee67-abd9-4a86-8c16-8d39af8c23bf
[I 09:26:20.979 LabApp] Adapting to protocol v5.0 for kernel 299cee67-abd9-4a86-8c16-8d39af8c23bf
[I 09:27:03.190 LabApp] New terminal with automatic name: 1
TermSocket.open: 1
TermSocket.open: Opened 1
[I 09:30:20.974 LabApp] Saving file at /test_kernels/test_golang.ipynb

```

**Comment by djhworld** [comment]
I'm experiencing this too

Works fine in jupyter notebook, but not in jupyterlab

No errors are being thrown in the logs, just all cells hang, as if they are waiting for something. 


I've noticed the dot in the top right corner just remains in the state `"Kernel Connected"` state (jupyterlab)

![screen shot 2018-02-21 at 10 36 19](https://user-images.githubusercontent.com/529730/36475583-1582ec82-16f3-11e8-9ed8-71702d01c3da.png)

Whereas in jupyternotebook it changes to "Kernel Idle"

![screen shot 2018-02-21 at 10 37 44](https://user-images.githubusercontent.com/529730/36475667-47706d50-16f3-11e8-95bb-9e9689dc6021.png)

**Comment by stoneyv** [comment]
I have tried to attach a delve or gdb debugger to the running process without success.  It might be possible to set the key in the configuration file to an empty string and rebuild so that I can read the messages using wireshark or tcpdump.  I see the message packets in wireshark or tcpdump, but they are encrypted to keep other users from injecting messages.  I am new to golang so it is difficult for me to make progress.

**Comment by SpencerPark** [comment]
Hi guys, I am able to reproduce these results and I believe I know where the problem is: for backwards compatibility the notebook would look past the fact that some kernels did not send busy-idle wrappers around all requests because it used to be only required for code execution. When the notebook first opens a `kernel_info_request` is made that the kernel properly replies to but without the busy-idle and I think that is causing the fronted to get stuck thinking that the request is not yet finished. I can look into this very soon.

On a side not in case you are curious, for debugging jupyter related things I use the chrome dev tools network tab. If you open that up and click on the `WS` button that will set the filter to view the websocket requests (which is what the browser is using to communicate with the kernel). With this open first you can start up a kernel and watch/inspect the requests. After starting the kernel click the `channels?...` to see the view in the following images. The green requests are messages sent from the browser to the kernel and the white are from kernel to browser.

Gophernotes - with this bug
![go-kernel-debug](https://user-images.githubusercontent.com/9256594/36518929-948a76d6-1756-11e8-8d82-f4cb7410e302.png)

IJava - for reference of working example
![java-kernel-debug](https://user-images.githubusercontent.com/9256594/36518942-adb0f4dc-1756-11e8-9b89-3d554b6e53b5.png)
